% Pander
% Date de cré
ation du rapport: `r format(Sys.time(),"%d.%m.%Y %H:%M")`

<div id="doc-content">


Pander
============
```{r set_knitr_chunk_options}
opts_chunk$set(echo=FALSE,message=FALSE,results = "asis") # important for making sure the output will be well formatted.
```
 
```{r load_pander_methods}
require(pander)
replace.print.methods <- function(PKG_name = "pander") {
   PKG_methods <- as.character(methods(PKG_name))
   print_methods <- gsub(PKG_name, "print", PKG_methods)
   for(i in seq_along(PKG_methods)) {
      f <- eval(parse(text=paste(PKG_name,":::", PKG_methods[i], sep = ""))) # the new function to use for print
      assign(print_methods[i], f, ".GlobalEnv")
   }   
}
replace.print.methods()
## The following might work with some tweaks:
## print <- function (x, ...) UseMethod("pander")
```
Some text explaining the analysis we are doing
```{r}
summary(cars)# a summary table

fit <- lm(dist~speed, data = cars)
fit

plot(cars) # a plot

```


#Data set selection
```{r echo=T,results='asis', tidy.opts=list(width.cutoff=180)}
library(table2html)
f <- "C:/Documents and Settings/fbally/git/table2html/table2html/inst/ignore/test.xml"
parse.xml(xml.doc)
ftable(Titanic, col.vars=c(1,2))
```

Line table:

----------- ------- --------------- -------------------------
   First    row                12.0 Example of a row that
                                    spans multiple lines.

  Second    row                 5.0 Here's another one. Note
                                    the blank line between
                                    rows.
----------- ------- --------------- -------------------------


Grid table:

+--------------------------------------------------------------------+
| Grid table                                                         |
+===============================+===============+====================+
| Fruit                         | Price         | Advantages         |
+-------------------------------+---------------+--------------------+
|  Fruits       | Bananas       | $1.34         | - built-in wrapper |
|               |               |               | - bright color     |
+               +---------------+---------------+--------------------+
|               | Oranges       | $2.10         | - cures scurvy     |
|               |               |               | - tasty            |
+---------------+---------------+---------------+--------------------+

Pipe table:

| Right | Left | Default | Center |
|------:|:-----|---------|:------:|
|   12  |  12  |    12   |    12  |
|  123  |  123 |   123   |   123  |
|    1  |    1 |     1   |     1  |


</div>